# Calculate allele specific reads for RASQUAL (ASVCF): 
parallel -j12 bash rasqual/vcf2asvcf.sh ../processed_data/genotype/phasing_with_1kg/phased_and_imputed_gprobs/phased_and_imputed.chr{}.vcf.gz ::: {1..22} X
parallel tabix -p vcf ../processed_data/genotype/phasing_with_1kg/phased_and_imputed_gprobs/phased_and_imputed.chr{}.rename.dr2.hwe.indellt51.rnasample.hg19.vcf.new.gz ::: {1..22} X
bcftools concat -Oz -o ../processed_data/genotype/phasing_with_1kg/phased_and_imputed_gprobs/phased_and_imputed.all.rename.dr2.hwe.indellt51.rnasample.hg19.vcf.new.gz ../processed_data/genotype/phasing_with_1kg/phased_and_imputed_gprobs/phased_and_imputed.chr{1..22}.rename.dr2.hwe.indellt51.rnasample.hg19.vcf.new.gz ../processed_data/genotype/phasing_with_1kg/phased_and_imputed_gprobs/phased_and_imputed.chrX.rename.dr2.hwe.indellt51.rnasample.hg19.vcf.new.gz
tabix -p vcf ../processed_data/genotype/phasing_with_1kg/phased_and_imputed_gprobs/phased_and_imputed.all.rename.dr2.hwe.indellt51.rnasample.hg19.vcf.new.gz


# Cleanup intermediate files generated by ASVCF: 
parallel -j12 bash rasqual/vcf2asvcf.cleanup.sh ../processed_data/genotype/phasing_with_1kg/phased_and_imputed_gprobs/phased_and_imputed.chr{}.vcf.gz ::: {1..22} X
