color=c('#e6acac', '#e5cf73', '#00e6d6', '#4400ff', '#f22000', '#737156', '#005f66', '#af8fbf', '#33170d', '#5c7300', '#86aab3', '#7a0099', '#f2853d', '#74d900', '#00aaff', '#e680ff', '#8c5b23', '#b6f2be', '#1d4b73', '#661a42', '#f2a200', '#004d1f', '#0057d9', '#f23d85', '#00ffaa', '#120d33', '#a6002c')
tissue_full=c('Adipose_Subcutaneous','Adipose_Visceral_Omentum','Adrenal_Gland','Artery_Aorta','Artery_Coronary','Artery_Tibial','Brain_Anterior_cingulate_cortex_BA24','Brain_Caudate_basal_ganglia','Brain_Cerebellar_Hemisphere','Brain_Cerebellum','Brain_Cortex','Brain_Frontal_Cortex_BA9','Brain_Hippocampus','Brain_Hypothalamus','Brain_Nucleus_accumbens_basal_ganglia','Brain_Putamen_basal_ganglia','Breast_Mammary_Tissue','Cells_EBV-transformed_lymphocytes','Cells_Transformed_fibroblasts','Colon_Sigmoid','Colon_Transverse','SF','Esophagus_Gastroesophageal_Junction','Esophagus_Mucosa','Esophagus_Muscularis','HCASMC','Heart_Atrial_Appendage','Heart_Left_Ventricle','Liver','Lung','Muscle_Skeletal','Nerve_Tibial','Ovary','Pancreas','Pituitary','Prostate','Skin_Not_Sun_Exposed_Suprapubic','Skin_Sun_Exposed_Lower_leg','Small_Intestine_Terminal_Ileum','Spleen','Stomach','Testis','Thyroid','Uterus','Vagina','Whole_Blood')
tissue_pretty=c('Adipose - Subcutaneous','Adipose - Visceral (Omentum)','Adrenal - Gland','Artery - Aorta','Artery - Coronary','Artery - Tibial','Brain - Anterior - cingulate - cortex (BA24)','Brain - Caudate (basal ganglia)','Brain - Cerebellar Hemisphere','Brain - Cerebellum','Brain - Cortex','Brain - Frontal Cortex (BA9)','Brain - Hippocampus','Brain - Hypothalamus','Brain - Nucleus accumbens (basal ganglia)','Brain - Putamen (basal ganglia)','Breast - Mammary Tissue','Cells - EBV-transformed lymphocytes','Cells - Transformed fibroblasts','Colon - Sigmoid','Colon - Transverse','SF','Esophagus - Gastroesophageal Junction','Esophagus - Mucosa','Esophagus - Muscularis','HCASMC','Heart - Atrial Appendage','Heart - Left Ventricle','Liver','Lung','Muscle - Skeletal','Nerve - Tibial','Ovary','Pancreas','Pituitary','Prostate','Skin - Not Sun Exposed (Suprapubic)','Skin - Sun Exposed (Lower leg)','Small Intestine - Terminal Ileum','Spleen','Stomach','Testis','Thyroid','Uterus','Vagina','Whole - Blood')
tissue_abbr=c('Adipose','Adipose','Adrenal Gland','Artery','Artery','Artery','Brain','Brain','Brain','Brain','Brain','Brain','Brain','Brain','Brain','Brain','Brain','LCL','Fibroblasts','Colon','Colon','HCASMC','Esophagus','Esophagus','Esophagus','HCASMC','Heart','Heart','Liver','Lung','Muscle','Nerve','Ovary','Pancreas','Pituitary','Prostate','Skin','Skin','Intestine','Spleen','Stomach','Testis','Thyroid','Uterus','Vagina','Blood')

df1=data.frame(tissue_abbr=unique(tissue_abbr),color)
df2=data.frame(tissue_full,tissue_pretty,tissue_abbr)
output=merge(df1,df2,by='tissue_abbr')
output=output[,c('tissue_full','tissue_pretty','tissue_abbr','color')]
write.table(output,'shared/tissue_color.txt',quote=F,col.names=T,row.names=F,sep='\t')