library(dplyr)
gtex_tissue_color=read.table('../data/gtex/gtex_tissue_colors.txt',header=T,sep='\t')
tissue_color=rbind(gtex_tissue_color,data.frame(tissue_site_detail=c('HCASMC','SF'),tissue_site_detail_abbr=c('HCASMC','SF'),tissue_site_detail_id=c('hcasmc.rpkm','dase.sf.rpkm'),tissue_site=c('HCASMC','HCASMC'),tissue_color_hex=c('FF0066','FF0066'),tissue_color_rgb=c('255,0,102','255,0,102')))
tissue_color$tissue_color_hex=paste0('#',tissue_color$tissue_color_hex)
tissue_color=tissue_color%>%arrange(as.character(tissue_site_detail))
tissue_color$tissue=c("Adipose Tissue",
					"Adipose Tissue",
					"Adrenal Gland",
					"Blood Vessel",
					"Blood Vessel",
					"Blood Vessel",
					"Bladder",
					"Brain",
					"Brain",
					"Brain",
					"Brain",
					"Brain",
					"Brain",
					"Brain",
					"Brain",
					"Brain",
					"Brain",
					"Brain",
					"Brain",
					"Brain",
					"Breast",
					"LCL",
					"Fibroblast",
					"Cervix Uteri",
					"Cervix Uteri",
					"Colon",
					"Colon",
					"Esophagus",
					"Esophagus",
					"Esophagus",
					"Fallopian Tube",
					"HCASMC",
					"Heart",
					"Heart",
					"Kidney",
					"Liver",
					"Lung",
					"Salivary Gland",
					"Muscle",
					"Nerve",
					"Ovary",
					"Pancreas",
					"Pituitary",
					"Prostate",
					"HCASMC",
					"Skin",
					"Skin",
					"Small Intestine",
					"Spleen",
					"Stomach",
					"Testis",
					"Thyroid",
					"Uterus",
					"Vagina",
					"Blood")
write.table(tissue_color,'shared/tissue_color.txt',quote=F,col.names=T,row.names=F,sep='\t')
